CREATE TABLE IF NOT EXISTS packages (
  id SERIAL PRIMARY KEY,
  slug VARCHAR(80) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  cost VARCHAR(80) NOT NULL,
  dates VARCHAR(120) NOT NULL,
  duration_banner VARCHAR(60),
  date_pill VARCHAR(120),
  description TEXT,
  includes_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  excludes_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  pickup_point VARCHAR(255),
  note TEXT,
  image_url TEXT NOT NULL,
  deposit_required INTEGER NOT NULL CHECK (deposit_required >= 0),
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE packages
ADD COLUMN IF NOT EXISTS hidden BOOLEAN NOT NULL DEFAULT FALSE;

CREATE TABLE IF NOT EXISTS reviews (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  review_text TEXT NOT NULL,
  rating INTEGER NOT NULL DEFAULT 5 CHECK (rating >= 1 AND rating <= 5),
  approved BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS customers (
  id SERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  phone VARCHAR(20) UNIQUE NOT NULL,
  notes TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS bookings (
  id SERIAL PRIMARY KEY,
  booking_code VARCHAR(32) UNIQUE NOT NULL,
  customer_id INTEGER NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  package_id INTEGER NOT NULL REFERENCES packages(id) ON DELETE CASCADE,
  payment_option VARCHAR(16) NOT NULL CHECK (payment_option IN ('full', 'space')),
  promo_code VARCHAR(40),
  original_total_amount INTEGER NOT NULL DEFAULT 0 CHECK (original_total_amount >= 0),
  discount_amount INTEGER NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
  total_amount INTEGER NOT NULL CHECK (total_amount >= 0),
  amount_paid INTEGER NOT NULL DEFAULT 0 CHECK (amount_paid >= 0),
  balance INTEGER NOT NULL CHECK (balance >= 0),
  status VARCHAR(40) NOT NULL DEFAULT 'Awaiting payment',
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payments (
  id SERIAL PRIMARY KEY,
  payment_code VARCHAR(32) UNIQUE NOT NULL,
  booking_id INTEGER REFERENCES bookings(id) ON DELETE SET NULL,
  phone VARCHAR(20) NOT NULL,
  promo_code VARCHAR(40),
  original_total_amount INTEGER,
  discounted_total_amount INTEGER,
  discount_amount INTEGER NOT NULL DEFAULT 0,
  amount INTEGER NOT NULL CHECK (amount > 0),
  reference VARCHAR(64) NOT NULL,
  stk_status VARCHAR(20) NOT NULL DEFAULT 'Pending',
  checkout_request_id VARCHAR(120),
  merchant_request_id VARCHAR(120),
  response_description TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS promo_code VARCHAR(40);

ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS original_total_amount INTEGER;

ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS discount_amount INTEGER;

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS promo_code VARCHAR(40);

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS original_total_amount INTEGER;

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS discounted_total_amount INTEGER;

ALTER TABLE payments
ADD COLUMN IF NOT EXISTS discount_amount INTEGER;

CREATE TABLE IF NOT EXISTS assistant_messages (
  id SERIAL PRIMARY KEY,
  source VARCHAR(40) NOT NULL,
  topic VARCHAR(120) NOT NULL,
  summary TEXT NOT NULL,
  unanswered BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gallery_items (
  id SERIAL PRIMARY KEY,
  src TEXT NOT NULL,
  location VARCHAR(120) NOT NULL,
  visible BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS announcements (
  id SERIAL PRIMARY KEY,
  title VARCHAR(160) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Draft',
  body TEXT NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS promo_codes (
  id SERIAL PRIMARY KEY,
  code VARCHAR(40) UNIQUE NOT NULL,
  discount VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS site_content (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  about_text TEXT NOT NULL,
  contact_phones TEXT NOT NULL,
  footer_email VARCHAR(160) NOT NULL,
  payment_instructions TEXT NOT NULL,
  footer_links TEXT NOT NULL,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
